# Generated by Django 3.2.4 on 2021-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('actor', models.CharField(max_length=25)),
                ('actress', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
